p2/force-app/main/default/objects/Exam_Question__c/Exam_Question__c.object-meta.xml
<CustomObject>
    <label>Exam Question</label>
    <nameField>
        <label>Exam Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

p2/force-app/main/default/objects/Exam_Question__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <label>Exam</label>
    <referenceTo>Exams__c</referenceTo>
    <relationshipLabel>Exam Questions</relationshipLabel>
    <relationshipName>Exam_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

p2/force-app/main/default/objects/Exam_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Exam Questions</relationshipLabel>
    <relationshipName>Exam_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

p2/force-app/main/default/objects/Exams__c/Exams__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exams Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2/force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2/force-app/main/default/objects/Question__c/fields/Question_Body__c.field-meta.xml
<CustomField>
    <fullName>Question_Body__c</fullName>
    <label>Question Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

p2/force-app/main/default/objects/Student_Answer__c/Student_Answer__c.object-meta.xml
<CustomObject>
    <label>Student Answer</label>
    <nameField>
        <label>Student Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

p2/force-app/main/default/objects/Student_Answer__c/fields/Exam_Question__c.field-meta.xml
<CustomField>
    <fullName>Exam_Question__c</fullName>
    <label>Exam Question</label>
    <referenceTo>Exam_Question__c</referenceTo>
    <relationshipLabel>Student Answers</relationshipLabel>
    <relationshipName>Student_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

p2/force-app/main/default/classes/ExamQController.cls
public class ExamQController {

    @AuraEnabled
    public static list<Exam_Question__c> examQs(string examTitle){
        list<Exam_Question__c> qList = [SELECT Question__r.Question_Body__c, Id FROM Exam_Question__c WHERE Exam__r.Name = :examTitle];
        return qList;
    }
    @AuraEnabled
    public static void studAns(list<Student_Answer__c> sAns){
        /*system.debug(sAns);
        Student_Answer__c response = new Student_Answer__c(Answer__c = sAns, Exam_Question__c = examId);
        list<Student_Answer__c> response = new list<Student_Answer__c>();
        for(Student_Answer__c sa: sAns){
        Student_Answer__c sa = new Student_Answer__c(Answer__c = sAns, Exam_Question__c = examId); 
        }*/
        insert sAns;
    }
}